### ISSUE TITLE
error: json: unknown field "commands"

### ISSUE THREAD

**Issue by xmlking** [hagmonk/kustom-spilo-postgres#1]
kustomization.yaml
```yaml
bases:
  - git::ssh://git@github.com/hagmonk/kustom-spilo-postgres

commonLabels:
  cluster-name: mini

# Target a different namespace
namespace: wonderland

# Prefix all resource names with this
namePrefix: production-

# Merge new environment variables in
configMapGenerator:
  - name: postgres
    behavior: merge
    literals:
      - PGUSER_ADMIN=lord-foobar

```

```bash
env SUPERUSER_PASSWORD=hovercraft REPLICATION_PASSWORD=eels  kustomize build
Error: accumulating resources: couldn't make target for path 'git::ssh://git@github.com/hagmonk/kustom-spilo-postgres': json: unknown field "commands"
```
